version: '3'
services:
  web:
    container_name: express-app
    image: express-app
    build: .
    command: /bin/bash -c "sleep 10; node index.js"
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"
  mongo:
    container_name: mongo
    image: "mongo"
    ports:
      - "27017:27017"